# Lab 1 - Warm-Up: Vectors and Dot Product for Perceptron

### Imports

In [1]:
import numpy as np
import pandas as pd

## Exercise 1: Scalars and Vectors

Objective: Understand how scalars and vectors are represented in NumPy.  
•	Define a scalar bias value  
•	Define an input vector and a weight vector  
•	Display their values  
Observation:  
•	Identify which variables represent learnable parameters  

In [2]:
b = 0.5
x = np.array([1.2, 0.7, -0.5])
w = np.array([0.8, -0.3, 1.1])

print("Bias (scalar):", b)
print("Input vector x:", x)
print("Weight vector w:", w)

Bias (scalar): 0.5
Input vector x: [ 1.2  0.7 -0.5]
Weight vector w: [ 0.8 -0.3  1.1]


## Exercise 2: Dot Product

Objective: Compute the dot product between input and weight vectors.  
•	Use NumPy to compute the dot product  
•	Print the output  
Interpretation:  
•	A positive value indicates the input lies on one side of the decision boundary  
•	A negative value indicates the opposite side  

In [3]:
dot_product = np.dot(w, x)
print("Dot product (w · x):", dot_product)

Dot product (w · x): 0.19999999999999996


## Exercise 3: Linear Combination

Objective: Compute the linear output of a neuron.  
•	Add bias to the dot product  
•	Observe how bias shifts the decision boundary  

In [4]:
y = dot_product + b
print("Linear output (y = w·x + b):", y)

Linear output (y = w·x + b): 0.7


## Exercise 4: Step Activation Function

Objective: Convert linear output into a binary decision.  
•	Implement a simple step activation function  
•	Apply it to the linear output  
Discussion Point:  
•	Why does a perceptron use an activation function?  

In [5]:
def step_activation(y):
    if y >= 0.5: return 1
    return 0

In [6]:
out = step_activation(y)
print("Perceptron output after step activation:", out)

Perceptron output after step activation: 1


## Exercise 5: Matrix as Batch of Samples

Objective: Understand batch processing.  
•	Define a matrix where each row is a data sample  
•	Print the matrix  
Key Idea:  
•	Deep learning models process data in batches for efficiency  

In [7]:
X = np.array([
    [1.2, 0.7, -0.5],
    [0.5, -1.2, 0.8],
    [-0.3, 0.4, 0.1],
    [1.0, 1.0, 1.0]
])

print(f"Input matrix:\n{X}")

Input matrix:
[[ 1.2  0.7 -0.5]
 [ 0.5 -1.2  0.8]
 [-0.3  0.4  0.1]
 [ 1.   1.   1. ]]


## Exercise 6: Batch Dot Product

Objective: Apply dot product to multiple samples simultaneously.  
•	Compute dot product between matrix and weight vector  
•	Add bias  
Insight:  
•	This operation is identical to computations performed in deep neural networks  

In [8]:
batch_y = np.dot(X, w) + b
batch_y

array([0.7 , 2.14, 0.25, 2.1 ])

In [9]:
batch_pred = np.array([step_activation(val) for val in batch_y])
batch_pred

array([1, 1, 0, 1])

## Post-Lab Reflection Questions

1.	What role do weights play in the dot product?

Weights determine the importance of each input feature in the dot product.
During the dot product, each input value is multiplied by its corresponding weight, and the results are summed. A larger weight increases the influence of that feature on the output, while a smaller or negative weight reduces or reverses its effect.

2.	How does bias affect the decision boundary?

Bias shifts the decision boundary of the perceptron without changing its orientation.
It allows the model to make predictions even when all input values are zero. Without bias, the decision boundary is forced to pass through the origin, which restricts the model’s flexibility.

3.	Why is dot product fundamental to neural networks?

The dot product is the core operation used to compute the weighted sum of inputs in every neuron.
All neural networks—from a single perceptron to deep neural networks—use dot products to combine inputs with learned weights before applying an activation function.

4.	How does batch computation help in training deep learning models?

Batch computation allows multiple input samples to be processed simultaneously using matrix operations.
This improves computational efficiency, better utilizes hardware like GPUs, and stabilizes learning by averaging gradients over multiple samples instead of updating weights for each sample individually.