# Lab 3: Introduction to TensorFlow for Deep Learning

## Program 1: Tensor Creation and Basic Operations

### Aim
To understand tensor creation and perform basic arithmetic operations using
TensorFlow

### Algorithm

1. Import TensorFlow library

In [1]:
import tensorflow as tf

2. Create scalar, vector, and matrix tensors

In [2]:
# Scalar
s1 = tf.constant(5)
s2 = tf.constant(3)

# Vector
v1 = tf.constant([1, 2, 3])
v2 = tf.constant([4, 5, 6])

# Matrix
m1 = tf.constant([[1, 2], [3, 4]])
m2 = tf.constant([[5, 6], [7, 8]])

3. Perform addition, multiplication, and matrix multiplication

In [3]:
scaler_add = s1 + s2
vec_add = v1 + v2
mat_mul = tf.matmul(m1, m2)

4. Display results

In [4]:
print("Scalar Addition:", scaler_add)
print("Vector Addition:", vec_add)
print("Matrix Multiplication:\n", mat_mul)

Scalar Addition: tf.Tensor(8, shape=(), dtype=int32)
Vector Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## Program 2: Linear Regression Using TensorFlow

### Aim
To implement a simple linear regression model using TensorFlow.

Algorithm

1. Import required libraries

In [5]:
import tensorflow as tf
import numpy as np

2. Create input and output data

In [6]:
x = np.array([1, 2, 3, 4, 5], dtype=float)
y = np.array([2, 4, 6, 8, 10], dtype=float)

3. Define a linear model

In [7]:
model = tf.keras.Sequential([
tf.keras.layers.Dense(units=1, input_shape=[1])
])

D:\python\python311\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4. Compile the model with loss and optimizer

In [8]:
model.compile(optimizer='sgd', loss='mean_squared_error')

5. Train the model

In [9]:
model.fit(x, y, epochs=10, verbose=0)

6. Test the model

In [10]:
print("Prediction for x=6:", model.predict(np.array([6])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
Prediction for x=6: [[11.024587]]


## Program 3: Simple Neural Network for Classification

### Aim
To build and train a neural network for binary classification.

### Algorithm

1. Import TensorFlow and dataset

In [11]:
import tensorflow as tf
from sklearn.datasets import make_classification

In [12]:
X, y = make_classification(n_samples=500, n_features=2, n_informative=2, n_redundant=0, n_classes=2)
X[:5], y[:5]

(array([[-3.17031066,  0.80769441],
        [ 1.01599677,  1.20477789],
        [ 0.04727788,  0.96484517],
        [-0.20491106, -1.57556269],
        [ 0.32364006, -2.14265246]]),
 array([1, 1, 1, 0, 0]))

2. Create a sequential neural network

In [13]:
model = tf.keras.Sequential()

3. Add dense layers with activation functions

In [14]:
model.add(tf.keras.layers.Dense(8, activation='relu', input_shape=(2,)))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

4. Compile the model

In [15]:
model.compile(optimizer='adam',
loss='binary_crossentropy',
metrics=['accuracy'])

5. Train and evaluate the model

In [16]:
model.fit(X, y, epochs=10, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)
print("Loss:", loss)
print("Accuracy:", acc)

Loss: 0.40428611636161804
Accuracy: 0.8640000224113464


## Exercises

1. Modify Program 1 to perform division and transpose operations

In [17]:
scaler_div = s1 / s2
vec_div = v1 / v2
mat_t = tf.transpose(m1)

print(f"Scaler Div {s1}/{s2}: {scaler_div}")
print(f"Vector Div {v1}/{v2}: {vec_div}")
print(f"Matrix Transpose \n(original\n{m1}) \n{mat_t}")

Scaler Div 5/3: 1.6666666666666667
Vector Div [1 2 3]/[4 5 6]: [0.25 0.4  0.5 ]
Matrix Transpose 
(original
[[1 2]
 [3 4]]) 
[[1 3]
 [2 4]]


2. Change the dataset in Program 2 and observe loss variation

In [18]:
x = np.array([1, -2, 3, -4, 5], dtype=float)
y = np.array([-1, 3, -5, 7, -9], dtype=float)

model = tf.keras.Sequential([
tf.keras.layers.Dense(units=1, input_shape=[1])
])

model.compile(optimizer='sgd', loss='mean_squared_error')
model.fit(x, y, epochs=100, verbose=0)

print("Prediction for x=6:", model.predict(np.array([6])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
Prediction for x=6: [[-10.359378]]


3. Add an extra hidden layer in Program 3 and compare accuracy

In [19]:
X, y = make_classification(n_samples=500, n_features=2, n_informative=2, n_redundant=0, n_classes=2)

model = tf.keras.Sequential([
tf.keras.layers.Dense(8, activation='relu', input_shape=(2,)),
tf.keras.layers.Dense(18, activation='tanh'),
tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
loss='binary_crossentropy',
metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)

print("Loss:", loss)
print("Accuracy:", acc)

Loss: 0.20317429304122925
Accuracy: 0.9120000004768372


4. Replace optimizer adam with sgd and analyze performance

In [20]:
X, y = make_classification(n_samples=500, n_features=2, n_informative=2, n_redundant=0, n_classes=2)

model = tf.keras.Sequential([
tf.keras.layers.Dense(8, activation='relu', input_shape=(2,)),
tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd',
loss='binary_crossentropy',
metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=0)
loss, acc = model.evaluate(X, y, verbose=0)

print("Loss:", loss)
print("Accuracy:", acc)

Loss: 0.2686035633087158
Accuracy: 0.8999999761581421


5. Implement multi-class classification using Softmax activation

In [21]:
X, y = make_classification(
    n_samples=500,
    n_features=10,
    n_informative=4,
    n_redundant=0,
    n_classes=4,
    n_clusters_per_class=1,
)

model = tf.keras.Sequential([
tf.keras.layers.Dense(8, activation='relu', input_shape=(10,)),
tf.keras.layers.Dense(16, activation='relu'),
tf.keras.layers.Dense(32, activation='tanh'),
tf.keras.layers.Dense(16, activation='relu'),
tf.keras.layers.Dense(4, activation='softmax')
])

model.compile(optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

model.fit(X, y, epochs=100, verbose=0)

loss, acc = model.evaluate(X, y, verbose=0)
print("Loss:", loss)
print("Accuracy:", acc)

Loss: 0.11214318126440048
Accuracy: 0.9639999866485596


## Exercise Questions

1. What is a tensor?

A Tensor is a N-dimensional Matrix:  

1.  A Scalar is a 0-dimensional tensor  
2.  A Vector is a 1-dimensional tensor  
3.  A Matrix is a 2-dimensional tensor  
4.  A n-dimentional tensor

A Tensor is a generalization of Vectors and Matrices to higher dimensions.  

2. Difference between NumPy arrays and TensorFlow tensors

NumPy arrays and TensorFlow tensors are both multi-dimensional arrays used for numerical computation in Python, but tensors are designed specifically for the demands of deep learning, offering GPU acceleration, automatic differentiation, and a computational graph. NumPy arrays are designed for general-purpose scientific computing on the CPU.

| Feature | NumPy Arrays | TensorFlow Tensors |
|------|-------------|-------------------|
| **Primary Use Case** | General scientific computing and data analysis. Works well with libraries like SciPy, Matplotlib, and Pandas. | Deep learning, machine learning model training, and distributed computing. |
| **Hardware Acceleration** | Primarily CPU-based. Requires additional libraries for limited GPU support. | Designed to run efficiently on CPUs, GPUs, TPUs, and distributed clusters. |
| **Automatic Differentiation** | No built-in support. Requires manual implementation or external libraries. | Built-in support for automatic differentiation, essential for backpropagation in neural networks. |
| **Execution Model** | Eager execution: operations run immediately, step by step. | Supports both eager execution and graph execution. |
| **Mutability** | Mutable: values can be modified after creation. | Immutable: tensors cannot be modified; new tensors are created for updates. |
| **Integration & Ecosystem** | Core of the Python scientific stack with a simple and lightweight API. | Part of the TensorFlow ecosystem with NumPy interoperability. |


3. What is an optimizer?

In deep learning, optimizers are crucial as algorithms that dynamically fine-tune a model’s parameters throughout the training process, aiming to minimize a predefined loss function. These specialized algorithms facilitate the learning process of neural networks by iteratively refining the weights and biases based on the feedback received from the data. Well-known optimizers in deep learning encompass Stochastic Gradient Descent (SGD), Adam, and RMSprop, each equipped with distinct update rules, learning rates, and momentum strategies, all geared towards the overarching goal of discovering and converging upon optimal model parameters, thereby enhancing overall performance.

4. Explain loss functions

A loss function is a mathematical way to measure how good or bad a model’s predictions are compared to the actual results.  

Loss functions are important because they:
1. Guide Model Training
2. Measure Performance
3. Affect learning behavior

5. What is backpropagation?

Backpropagation, short for Backward Propagation of Errors, is a key algorithm used to train neural networks by minimizing the difference between predicted and actual outputs. It works by propagating errors backward through the network, using the chain rule of calculus to compute gradients and then iteratively updating the weights and biases. Combined with optimization techniques like gradient descent, backpropagation enables the model to reduce loss across epochs and effectively learn complex patterns from data.